spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-abc123.us.auth0.com/.well-known/jwks.json